### ISSUE TITLE
Rename option

### ISSUE THREAD

**Issue by stevenvachon** [75lb/command-line-args#74] opened 2017-12-27 18:12 UTC
It'd be nice if we could do this:

```js
const args = commandLineArgs([
    { name: 'opt-name', type: Boolean, rename: 'optName' }
]);

console.log(args);
//-> { optName: true }
```

It would help make our code cleaner, by not needing `args['opt-name']` nor custom code to replace properties.

**Comment by 75lb** [comment] 2017-12-27 18:35
duplicate of #57

**Closed by 75lb** 2017-12-27 18:35 UTC
