### ISSUE TITLE
Rollup plugin Circular Dependency issue

### ISSUE THREAD

**Issue by dananderson** [75lb/command-line-args#99] opened 2019-03-08 05:42 UTC
command-line-args caused this error with rollup:

(!) Circular dependency: node_modules/command-line-args/lib/option.js -> node_modules/command-line-args/lib/option-flag.js -> node_modules/command-line-args/lib/option.js

A fix would be to move Option/OptionFlag.create to a new OptionFactory class file and update create callers to use the factory.

**Comment by 75lb** [comment] 2019-03-13 11:28
Hi, could you post a reproduction case please - some code I can debug and fix. Thanks.

**Comment by dananderson** [comment] 2019-03-13 14:11
Thanks for looking into this.

https://github.com/dananderson/command-line-args-cicular-dependency

```
npm
npm run rollup
node one.js
```

My rollup target environment is node with es6 classes. rollup produces one.js with a circular dependency warning. one.js is created, but running one.js results in a runtime error due to the circular dependency.

**Comment by 75lb** [comment] 2019-03-14 10:42
thanks for the reproduction case.

The option-flag module [is lazy-loaded at run time](https://github.com/75lb/command-line-args/blob/master/lib/option.js#L76) therefore does not cause a compile-time circular reference. This is a rollup issue caused by [a bug in rollup-plugin-commonjs](https://github.com/rollup/rollup-plugin-commonjs/issues/105).

Do you have a quick fix for this? If so, please drop me a PR. The long-term fix is to upgrade the command-line-args project to offer an ESM entry-point (as well as CJS). I'll do that when I next get chance.

**Comment by dananderson** [comment] 2019-03-16 00:41
Thanks for digging into the rollup stuff.

The root cause seems to be how rollup translates inline requires. I suspect it is not worth fixing on the rollup side because user land expects the existing behavior.. and es modules are coming.

The long term fix would be an es module. For the short term, it would be nice to get command-line-args working with rollup. I'll propose a PR next week and we can discuss if it fits into your project.

**Comment by 75lb** [comment] 2019-03-24 00:35
Fixed and released in [v5.1.0](https://github.com/75lb/command-line-args/releases/tag/v5.1.0).

**Closed by 75lb** 2019-03-24 00:35 UTC
