### ISSUE TITLE
UNKNOWN_OPTION could be optional

### ISSUE THREAD

**Issue by flipflopapp** [75lb/command-line-args#38] opened 2017-01-23 05:48 UTC
When I use an app that uses the npm module with mocha (and I want to pass some options to mocha and others to the module being tested), I see an UNKNOWN_OPTION error. For example, I want to pass --no-timeout to mocha.

**Comment by flipflopapp** [comment] 2017-01-23 05:56
It requires minor changes

https://github.com/flipflopapp/command-line-args

works for my usecase.

**Comment by 75lb** [comment] 2017-01-24 19:22
ok, thanks - i had a look at what you did.. I'm considering solutions for handling unknown options but won't be discarding them, as in your case. 

Closing as a near-duplicate of #25, which i'm working on as we speak.

**Closed by 75lb** 2017-01-24 19:22 UTC

**Comment by 75lb** [comment] 2017-01-24 19:28
btw, is there any reason you can't create a definition for `--no-timeout` if it's an option your app accepts?

**Comment by 75lb** [comment] 2017-01-28 17:47
i've almost finished implementing a new feature to allow unknown options.. could you send an example of how your app was failing with mocha please, so i can test it?

**Comment by flipflopapp** [comment] 2017-01-28 20:01
(oops late response - missed the mail notifications). I can create a --no-timeouts option in my app but I thought I would have to add options everytime I wanted to pass a new option to mocha. The command line looks like below,

$ mocha test/test-file.js --some_option_for_app --some_option_for_mocha

My nodejs app accepts some parameters from command line arguments. It was failing when it saw arguments that were meant for mocha. Please let me know if I can provide anymore information.

**Comment by 75lb** [comment] 2017-01-28 20:23
ok, thanks for the example - i understand what you're doing now, thanks.

**Comment by 75lb** [comment] 2017-01-28 20:56
with the new version of command-line-args, if you have this mocha script: 

```
/* demonstrates use in a mocha test script */
const assert = require('assert')
const commandLineArgs = require('../')

const options = commandLineArgs({ name: 'value', type: Number }, { partial: true })

describe('Array', function () {
  describe('#indexOf()', function () {
    it('should return -1 when the value is not present', function () {
      assert.equal(options.value, [ 1, 2, 3 ].indexOf(4))
    })
  })
})
```

you can run the script with a command like this and it will not throw a `UNKNOWN_OPTION` error: 

```
$ mocha --no-colors example/mocha.js --value -1


  Array
    #indexOf()
      ✓ should return -1 when the value is not present


  1 passing (7ms)
```

`options` will look like this: 

```
{
  "value": -1,
  "_unknown": [
    "--no-colors",
    "example/mocha.js"
  ]
}
```

**Comment by 75lb** [comment] 2017-01-28 22:14
i've released a beta version which implements this feature.. for details, see https://github.com/75lb/command-line-args/issues/25 and let me know your thoughts. Thanks!

**Comment by flipflopapp** [comment] 2017-01-29 16:15
Looks perfect. Thanks for the quick turnaround. Cheers
