### ISSUE TITLE
Want required arguments, not purely optional arguments

### ISSUE THREAD

**Issue by jgberg** [75lb/command-line-args#60] opened 2017-09-23 00:25 UTC
It seems that one cannot specify that an argument be provided. I want to define an 'option' that is required such that, for example, an option named "file" to be provided as "--file" and it is to be "required', meaning that if it is not provided, a 'missing required option" error be thrown with an indication of the missing required option.

Having required arguments is a standard feature of numerous commands of Linux/UNIX which this library emulates.

**Comment by 75lb** [comment] 2017-11-06 23:13
Closing as duplicate of https://github.com/75lb/command-line-args/issues/34. Please [see here](https://github.com/75lb/command-line-args/blob/master/example/validate.js) for a simple validation example.

**Closed by 75lb** 2017-11-06 23:13 UTC

**Comment by davidmaxwaterman** [comment] 2018-02-27 00:34
that 'see here' gives a 404

kind of a shame this isn't handled by this lib.

**Comment by 75lb** [comment] 2018-02-27 09:00
@davidmaxwaterman [read this](https://github.com/75lb/command-line-args/wiki/Validation#why-is-validation-not-built-into-the-module)
