### ISSUE TITLE
Allow unknown cli arguments

### ISSUE THREAD

**Issue by scaljeri** [75lb/command-line-args#37] opened 2017-01-19 12:40 UTC
I have this case in which I don't know all the cli arguments. It would be nice if there was an options to disable the `unknown option` check.

**Comment by 75lb** [comment] 2017-01-19 12:41
duplicate of #25

**Closed by 75lb** 2017-01-19 12:41 UTC

**Comment by 75lb** [comment] 2017-01-28 22:13
i've released a beta version which implements this feature.. for details, see https://github.com/75lb/command-line-args/issues/25 and let me know your thoughts. Thanks!
